Improve minibox scripts
Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

diff --git a/Scripts/minibox-ls b/Scripts/minibox-ls
--- a/Scripts/minibox-ls
+++ b/Scripts/minibox-ls
@@ -1,31 +1,40 @@
-#!/bin/dash
+#!/bin/zsh
 
 # SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
 #
 # SPDX-License-Identifier: Apache-2.0
 
-set -eu
+setopt errexit nounset nullglob pipefail warn_create_global
 
-usage() {
-	printf 'Usage: minibox ls [BaseImages]\n'
-}
-
+MINIBOX_VERSION="0.1.0"
 : "${MINIBOX_DATA_DIR:=$HOME/Library/Application Support/tokyo.kaito.MiniboxSwift.minibox}"
 
-MINIBOX_BASE_IMAGE_DIR="${MINIBOX_DATA_DIR}/BaseImages"
+usage() {
+	printf 'minibox-ls: Lists the images available in the Minibox data directory.\n'
+	printf 'Usage: minibox-ls [all|base-images]\n'
+	printf '  all  Lists all the images in human-readable format.\n'
+}
 
-if [ "$#" -eq 0 ]; then
-	printf '%s:\n' "${MINIBOX_BASE_IMAGE_DIR}"
-	ls "${MINIBOX_BASE_IMAGE_DIR}"
-else
-	case "$1" in
-	BaseImages)
-		ls "${MINIBOX_BASE_IMAGE_DIR}"
-		;;
-	*)
-		printf 'Unknown argument: %s\n' "$1" >&2
-		usage >&2
-		exit 64
-		;;
-	esac
+minibox-ls-all() {
+	local bundlePath baseImageName
+	for bundlePath in "${MINIBOX_DATA_DIR}/BaseImages"/*.miniboxvm(N/); do
+		baseImageName="${bundlePath:t:r}"
+		printf 'BaseImage=%s\n' "${baseImageName}"
+		printf '  # To run this miniboxvm bundle with GUI:\n'
+		printf '  minibox view --bundle-path=%q\n' "${bundlePath}"
+		printf '\n'
+		printf '  # To prepare this base image for GitHub:\n'
+		printf '  minibox prepare --base-image-name=%q --variant=github\n' "${baseImageName}"
+		printf '\n'
+	done
+}
+
+subcommand="minibox-ls-${1:-all}"
+
+if ! whence "${subcommand}" >/dev/null 2>&1; then
+	printf 'ERROR: Unsupported subcommand: %s\n' "$1" >&2
+	usage >&2
+	exit 64
 fi
+
+"${subcommand}" "${@:2}"
diff --git a/Scripts/minibox-prepare b/Scripts/minibox-prepare
--- a/Scripts/minibox-prepare
+++ b/Scripts/minibox-prepare
@@ -10,35 +10,53 @@ setopt errexit nounset nullglob pipefail warn_create_global
 export MINIBOX_DATA_DIR
 
 usage() {
-	printf 'Usage: minibox prepare --base-image-name=NAME --variant=NAME\n'
-	printf '  --base-image-name=NAME  Name of the base image to prepare. Mandatory.\n'
+	printf 'Usage: minibox-prepare --base-image-name=NAME --variant=NAME\n'
+	printf '  --baseImageName=NAME  Name of the base image to prepare. Mandatory.\n'
 	printf '  --variant=NAME          Variant name for preparation process. Mandatory.\n'
-	printf '  --agentic-advice        Enable agentic advice for setup using Ollama.\n'
 	printf '  --no-sudo               Do not use sudo for operations. Optional.\n'
 	printf '  --force                 Force to overwrite existing files.\n'
+	printf '  --skip-steps=S1,S2      Comma-separated list of step names to skip. Optional.\n'
 	printf '  --step=NAME	          Step name to execute. Internal use only.\n'
 }
 
 typeset -A opts
+typeset -a posArgs
 while (($#)); do
-	case $1 in
-	--) break ;;
-	--*=*) opts[${1%%=*}]=${1#*=}; shift ;;
-	--*) opts[$1]=${${2-}##--*}; shift ${${opts[$1]:+2}:-1} ;;
-	*) shift ;;
-	esac
+	if [[ $1 == -- ]]; then
+		posArgs+=("${@:2}")
+		set --
+		break
+	elif [[ $1 == --?*=* ]]; then
+		opts[${1%%=*}]="${1#*=}"
+	elif [[ $1 == --?* ]]; then
+		if [[ ${2:---} == --* ]]; then
+			opts[$1]=''
+		else
+			opts[$1]="$2"
+			shift
+		fi
+	else
+		posArgs+=("$1")
+	fi
+	shift
 done
 
-if [[ -z ${opts[--variant]-} ]]; then
-	printf 'ERROR: --variant is required.\n' >&2
-	usage >&2
-	exit 64
-fi
+getoption() {
+	if ((${+opts[$1]})); then
+		printf '%s' "${opts[$1]}"
+	elif [[ ${2:-} == required ]]; then
+		printf 'ERROR: %s is required.\n' "$1" >&2
+		usage >&2
+		exit 64
+	fi
+}
 
-prepare_command="minibox-prepare-$opts[--variant]"
+variant=$(getoption --variant required)
+
+prepare_command="minibox-prepare-${variant}"
 
 if ! whence "${prepare_command}" >/dev/null 2>&1; then
-	printf 'ERROR: Unsupported variant: %s\n' "$opts[--variant]" >&2
+	printf 'ERROR: Unsupported variant: %s\n' "${variant}" >&2
 	printf 'ERROR: Command %s not found.\n' "${prepare_command}" >&2
 	usage >&2
 	exit 127
diff --git a/Scripts/minibox-prepare-github b/Scripts/minibox-prepare-github
--- a/Scripts/minibox-prepare-github
+++ b/Scripts/minibox-prepare-github
@@ -10,35 +10,55 @@ setopt errexit nounset nullglob pipefail warn_create_global
 export MINIBOX_DATA_DIR
 
 usage() {
-	printf 'Usage: minibox-prepare-github --base-image-name=NAME --variant=NAME\n'
+	printf 'Usage: minibox-prepare-github --base-image-name=NAME\n'
 	printf '  --base-image-name=NAME  Name of the base image to prepare. Mandatory.\n'
-	printf '  --variant=NAME          Variant name for preparation process. Mandatory.\n'
 	printf '  --no-sudo               Do not use sudo for operations. Optional.\n'
 	printf '  --force                 Force to overwrite existing files.\n'
+	printf '  --skip-steps=S1,S2      Comma-separated list of step names to skip. Optional.\n'
 	printf '  --step=NAME	          Step name to execute. Internal use only.\n'
 }
 
 typeset -A opts
+typeset -a posArgs
 while (($#)); do
-	case $1 in
-	--) break ;;
-	--*=*) opts[${1%%=*}]=${1#*=}; shift ;;
-	--*) opts[$1]=${${2-}##--*}; shift ${${opts[$1]:+2}:-1} ;;
-	*) shift ;;
-	esac
+	if [[ $1 == -- ]]; then
+		posArgs+=("${@:2}")
+		set --
+		break
+	elif [[ $1 == --?*=* ]]; then
+		opts[${1%%=*}]="${1#*=}"
+	elif [[ $1 == --?* ]]; then
+		if [[ ${2:---} == --* ]]; then
+			opts[$1]=''
+		else
+			opts[$1]="$2"
+			shift
+		fi
+	else
+		posArgs+=("$1")
+	fi
+	shift
 done
 
-if [[ -z ${opts[--base-image-name]-} ]]; then
-	printf 'ERROR: --base-image-name is required.\n' >&2
-	usage >&2
-	exit 64
-fi
+getoption() {
+	if ((${+opts[$1]})); then
+		printf '%s' "${opts[$1]}"
+	elif [[ ${2:-} == required ]]; then
+		printf 'ERROR: %s is required.\n' "$1" >&2
+		usage >&2
+		exit 64
+	fi
+}
 
-srcBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${opts[--base-image-name]}.miniboxvm"
-destBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${opts[--base-image-name]}_${opts[--variant]}.miniboxvm"
-volumePath="${MINIBOX_DATA_DIR}/Volumes/${opts[--base-image-name]}_${opts[--variant]}"
+baseImageName=$(getoption --base-image-name required)
+noSudo=$(getoption --no-sudo)
+skipSteps=$(getoption --skip-steps)
+
+srcBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${baseImageName}.miniboxvm"
+destBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${baseImageName}_github.miniboxvm"
+volumePath="${MINIBOX_DATA_DIR}/Volumes/${baseImageName}_github"
 scriptPath="$0"
-if ((${+opts[--no-sudo]})); then
+if ((${+noSudo})); then
 	sudo=:
 else
 	sudo=sudo
@@ -60,6 +80,7 @@ minibox-prepare-github-clone() {
 			rm -rf "${destBaseImagePath}"
 		else
 			printf 'ERROR: Base image already exists: %s\n' "${destBaseImagePath}" >&2
+			printf 'ERROR: Try again with --force to overwrite.\n' >&2
 			exit 1
 		fi
 	fi
